"""Add ai_summary to documents

Revision ID: 5a47b5df3f00
Revises: e5f6a7b8c9d0
Create Date: 2025-12-16 16:01:35.864089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '5a47b5df3f00'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('documents', sa.Column('ai_summary', sa.Text(), nullable=True), schema='sred_ds')
    op.add_column('documents', sa.Column('ai_summary_generated_at', sa.DateTime(timezone=True), nullable=True), schema='sred_ds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('documents', 'ai_summary_generated_at', schema='sred_ds')
    op.drop_column('documents', 'ai_summary', schema='sred_ds')
    # ### end Alembic commands ###