"""Initial schema with all tables in bc_legal_ds

Revision ID: 7e84499ef797
Revises: 
Create Date: 2025-11-08 20:55:42.081467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '7e84499ef797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create bc_legal_ds schema
    op.execute('CREATE SCHEMA IF NOT EXISTS bc_legal_ds')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('plan_tier', sa.String(length=50), nullable=True),
    sa.Column('tenancy_type', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain'),
    schema='bc_legal_ds'
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['bc_legal_ds.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['bc_legal_ds.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='bc_legal_ds'
    )
    op.create_table('matters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('matter_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('matter_type', sa.String(length=100), nullable=False),
    sa.Column('matter_status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('lead_attorney_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['bc_legal_ds.companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['bc_legal_ds.users.id'], ),
    sa.ForeignKeyConstraint(['lead_attorney_user_id'], ['bc_legal_ds.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['bc_legal_ds.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bc_legal_ds.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_index(op.f('ix_bc_legal_ds_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True, schema='bc_legal_ds')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bc_legal_ds.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_index(op.f('ix_bc_legal_ds_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='bc_legal_ds')
    op.create_table('user_groups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['bc_legal_ds.users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['bc_legal_ds.groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bc_legal_ds.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    schema='bc_legal_ds'
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['bc_legal_ds.companies.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['bc_legal_ds.matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bc_legal_ds.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_subtype', sa.String(length=100), nullable=True),
    sa.Column('document_title', sa.String(length=500), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('document_status', sa.String(length=50), nullable=False),
    sa.Column('is_current_version', sa.Boolean(), nullable=True),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('parent_document_id', sa.UUID(), nullable=True),
    sa.Column('root_document_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('confidentiality_level', sa.String(length=50), nullable=False),
    sa.Column('is_privileged', sa.Boolean(), nullable=True),
    sa.Column('privilege_attorney_client', sa.Boolean(), nullable=True),
    sa.Column('privilege_work_product', sa.Boolean(), nullable=True),
    sa.Column('privilege_settlement', sa.Boolean(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('opposing_counsel', sa.String(length=255), nullable=True),
    sa.Column('opposing_party', sa.String(length=255), nullable=True),
    sa.Column('court_jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('judge_name', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('contract_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('contract_effective_date', sa.Date(), nullable=True),
    sa.Column('contract_expiration_date', sa.Date(), nullable=True),
    sa.Column('governing_law', sa.String(length=100), nullable=True),
    sa.Column('discovery_type', sa.String(length=100), nullable=True),
    sa.Column('propounding_party', sa.String(length=255), nullable=True),
    sa.Column('responding_party', sa.String(length=255), nullable=True),
    sa.Column('discovery_number', sa.String(length=100), nullable=True),
    sa.Column('response_due_date', sa.Date(), nullable=True),
    sa.Column('response_status', sa.String(length=50), nullable=True),
    sa.Column('exhibit_number', sa.String(length=100), nullable=True),
    sa.Column('correspondence_type', sa.String(length=50), nullable=True),
    sa.Column('cc', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('review_deadline', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('review_instructions', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('text_extracted', sa.Boolean(), nullable=True),
    sa.Column('indexed_for_search', sa.Boolean(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('extraction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['bc_legal_ds.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['bc_legal_ds.users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['bc_legal_ds.matters.id'], ),
    sa.ForeignKeyConstraint(['parent_document_id'], ['bc_legal_ds.documents.id'], ),
    sa.ForeignKeyConstraint(['root_document_id'], ['bc_legal_ds.documents.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['bc_legal_ds.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_table('matter_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_role', sa.String(length=50), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['bc_legal_ds.users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['bc_legal_ds.matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bc_legal_ds.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['bc_legal_ds.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('context_chunks', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['bc_legal_ds.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bc_legal_ds'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages', schema='bc_legal_ds')
    op.drop_table('document_chunks', schema='bc_legal_ds')
    op.drop_table('matter_access', schema='bc_legal_ds')
    op.drop_table('documents', schema='bc_legal_ds')
    op.drop_table('conversations', schema='bc_legal_ds')
    op.drop_table('user_groups', schema='bc_legal_ds')
    op.drop_index(op.f('ix_bc_legal_ds_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='bc_legal_ds')
    op.drop_table('refresh_tokens', schema='bc_legal_ds')
    op.drop_index(op.f('ix_bc_legal_ds_password_reset_tokens_token_hash'), table_name='password_reset_tokens', schema='bc_legal_ds')
    op.drop_table('password_reset_tokens', schema='bc_legal_ds')
    op.drop_table('matters', schema='bc_legal_ds')
    op.drop_table('users', schema='bc_legal_ds')
    op.drop_table('groups', schema='bc_legal_ds')
    op.drop_table('companies', schema='bc_legal_ds')
    # ### end Alembic commands ###

    # Drop bc_legal_ds schema
    op.execute('DROP SCHEMA IF EXISTS bc_legal_ds CASCADE')